[package]
name = "cyc_filt"
version = "0.1.0"
edition = "2021"
authors = ["Chentao Yang yangchentao at genomics.cn"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"

